name: rbx_wallet
description: A new Flutter project.

publish_to: "none"

version: 2.0.2+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.5
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.4
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.15
  timeago: ^3.2.2
  url_launcher: ^6.1.4
  process_run: ^0.12.3+2
  font_awesome_flutter: ^10.1.0
  flutter_window_close: ^0.2.2
  desktop_window: ^0.4.0
  dart_ipify: ^1.1.1
  flutter_launcher_icons: ^0.12.0
  process: ^4.2.4
  flutter_awesome_select: ^6.4.0
  path_provider: ^2.0.11
  uuid: ^3.0.6
  file_picker: ^4.6.1
  file_saver: ^0.2.4
  qr_flutter: ^4.0.0
  animate_icons: ^2.0.0
  timezone: ^0.9.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  pointycastle: ^3.6.0
  base58check: ^2.0.0
  convert: ^3.0.2
  url_strategy: ^0.2.0
  dart_bip66: ^2.0.1
  window_manager: ^0.3.0
  secp256k1: ^0.3.0
  dots_indicator: ^2.1.0
  carousel_slider: ^4.1.1
  pinch_zoom: ^1.0.0
  date_count_down: ^2.1.0
  video_player: ^2.4.5
  archive: ^3.3.1
  pie_chart: ^5.3.2
  # dio_logging_interceptor: ^1.0.1
  csv: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  pausable_timer: ^1.0.0+7
  context_menus: ^1.0.2
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.3
  webviewx: ^0.2.2
  uni_links_desktop: ^0.1.6
  riverpod_annotation: ^2.1.2
  riverpod_generator: ^2.1.5
  js: ^0.6.5
  candlesticks: ^2.1.0
  bitsdojo_window: ^0.1.2
  syncfusion_flutter_charts: ^21.2.4
  flutter_spinkit: ^5.2.1



dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.3.1
  msix: ^3.6.2
  

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/connector/
    - assets/images/icons/
    - assets/env/
    - assets/fonts/
    - assets/js/
    - assets/docs/
    - assets/data/
    - assets/html/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Medium.ttf
          weight: 500 
        - asset: assets/fonts/Mukta-SemiBold.ttf
          weight: 600 
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700 

flutter_gen:
  output: lib/generated

msix_config:
  display_name: RBX Wallet
  publisher_display_name: ReserveBlock
  identity_name: io.reserveblock
  msix_version: 1.0.0.0
  logo_path: C:\Users\tyler\Projects\rbx-wallet-gui\assets\images\icon.png
  capabilities: internetClient

flutter_icons:
  ios: false
  android: false
  macos: true
  windows: true
  image_path: "assets/images/icon.png"


# flutter_native_splash:
#   background_image: 'resources/splash-bg.png'
#   image: 'resources/splash-fg.png'